enum ActionType {
    GET_POST_REQUEST,
    GET_POST_SUCCESS,
    GET_POST_FAIL,
    SELECT_POST_REQUEST,
    SELECT_POST_SUCCESS,
    SELECT_POST_FAIL,
    POST_ADDING,
    ADD_POST_REQUEST,
    ADD_POST_SUCCESS,
    ADD_POST_FAIL
}
export default ActionType 